import type { Email } from "./types";

/**
 * Dados de demonstração — substituir pelas queries IMAP/Prisma
 * (`GET /api/emails?pasta=...`) quando o backend estiver disponível.
 */

const now = Date.now();
const hours = (h: number) => new Date(now - h * 3600_000).toISOString();

export const mockEmails: Email[] = [
  {
    id: "e1",
    message_id: "<1@malaca.com.br>",
    remetente: { nome: "Registro.br", email: "no-reply@registro.br" },
    destinatarios: [{ nome: "Você", email: "contato@malaca.com.br" }],
    assunto: "Renovação do domínio malaca.com.br confirmada",
    preview: "O pagamento foi processado e seu domínio está ativo por mais 12 meses.",
    html: "<p>Olá,</p><p>O pagamento foi processado e o domínio <strong>malaca.com.br</strong> está ativo por mais 12 meses.</p><p>Próximo vencimento: 14/08/2027.</p><p>Equipe Registro.br</p>",
    texto: "Domínio renovado por 12 meses.",
    data_envio: hours(1),
    lida: false,
    favorita: true,
    pasta: "inbox",
    anexos: [
      {
        id: "a1",
        email_id: "e1",
        nome: "recibo-dominio.pdf",
        tipo: "application/pdf",
        tamanho: 184320,
        caminho: "/storage/a1",
      },
    ],
  },
  {
    id: "e2",
    message_id: "<2@malaca.com.br>",
    remetente: { nome: "Camila Duarte", email: "camila@estudioalva.com" },
    destinatarios: [{ email: "contato@malaca.com.br" }],
    cc: [{ email: "financeiro@estudioalva.com" }],
    assunto: "Proposta revisada — identidade visual",
    preview: "Ajustei o escopo conforme conversamos ontem. Segue o PDF com as três fases.",
    html: "<p>Oi!</p><p>Ajustei o escopo conforme conversamos ontem. Segue o PDF com as três fases e o cronograma.</p><p>Qualquer coisa me chama.</p><p>— Camila</p>",
    texto: "Proposta revisada em anexo.",
    data_envio: hours(4),
    lida: false,
    favorita: false,
    pasta: "inbox",
    anexos: [
      {
        id: "a2",
        email_id: "e2",
        nome: "proposta-v2.pdf",
        tipo: "application/pdf",
        tamanho: 942080,
        caminho: "/storage/a2",
      },
      {
        id: "a3",
        email_id: "e2",
        nome: "moodboard.png",
        tipo: "image/png",
        tamanho: 2411724,
        caminho: "/storage/a3",
      },
    ],
  },
  {
    id: "e3",
    message_id: "<3@malaca.com.br>",
    remetente: { nome: "Monitoramento SMTP", email: "alerts@smtp.malaca.com.br" },
    destinatarios: [{ email: "contato@malaca.com.br" }],
    assunto: "DKIM válido · SPF válido · DMARC em quarentena",
    preview: "Relatório diário de autenticação dos servidores de e-mail do domínio.",
    html: "<p>Relatório diário de autenticação:</p><ul><li>SPF: pass</li><li>DKIM: pass (selector <code>mail</code>)</li><li>DMARC: policy quarantine</li></ul><p>Nenhuma falha de entrega nas últimas 24h.</p>",
    texto: "SPF pass, DKIM pass, DMARC quarantine.",
    data_envio: hours(9),
    lida: true,
    favorita: false,
    pasta: "inbox",
    anexos: [],
  },
  {
    id: "e4",
    message_id: "<4@malaca.com.br>",
    remetente: { nome: "Rafael Nunes", email: "rafael@oficinacoletiva.org" },
    destinatarios: [{ email: "contato@malaca.com.br" }],
    assunto: "Sobre o encontro de sexta",
    preview: "Consegui reservar a sala das 19h. Levo o projetor, você leva o café?",
    html: "<p>Consegui reservar a sala das 19h. Levo o projetor, você leva o café?</p>",
    texto: "Sala reservada às 19h.",
    data_envio: hours(27),
    lida: true,
    favorita: false,
    pasta: "inbox",
    anexos: [],
  },
  {
    id: "e5",
    message_id: "<5@malaca.com.br>",
    remetente: { nome: "Biblioteca Municipal", email: "avisos@bibliotecamunicipal.gov.br" },
    destinatarios: [{ email: "contato@malaca.com.br" }],
    assunto: "Devolução prevista para amanhã",
    preview: "Dois títulos do seu empréstimo vencem em 24 horas.",
    html: "<p>Dois títulos do seu empréstimo vencem em 24 horas. Renove pelo portal.</p>",
    texto: "Devolução amanhã.",
    data_envio: hours(50),
    lida: false,
    favorita: false,
    pasta: "inbox",
    anexos: [],
  },
  {
    id: "e6",
    message_id: "<6@malaca.com.br>",
    remetente: { nome: "Newsletter Tipografia", email: "letras@tipografiabr.news" },
    destinatarios: [{ email: "contato@malaca.com.br" }],
    assunto: "Edição 118 — o retorno das serifas expressivas",
    preview: "Cinco famílias tipográficas lançadas neste mês que merecem atenção.",
    html: "<p>Cinco famílias tipográficas lançadas neste mês que merecem atenção.</p>",
    texto: "Newsletter 118.",
    data_envio: hours(72),
    lida: true,
    favorita: false,
    pasta: "inbox",
    anexos: [],
  },
  {
    id: "e7",
    message_id: "<7@malaca.com.br>",
    remetente: { nome: "Você", email: "contato@malaca.com.br" },
    destinatarios: [{ nome: "Camila Duarte", email: "camila@estudioalva.com" }],
    assunto: "Re: Proposta revisada — identidade visual",
    preview: "Recebi, obrigado! Reviso hoje à noite e te respondo com os ajustes.",
    html: "<p>Recebi, obrigado! Reviso hoje à noite e te respondo com os ajustes.</p>",
    texto: "Recebi, obrigado.",
    data_envio: hours(3),
    lida: true,
    favorita: false,
    pasta: "sent",
    anexos: [],
  },
  {
    id: "e8",
    message_id: "<8@malaca.com.br>",
    remetente: { nome: "Você", email: "contato@malaca.com.br" },
    destinatarios: [{ email: "suporte@hospedagem.com.br" }],
    assunto: "Abertura de porta 587 para submission",
    preview: "Preciso liberar a porta 587 com STARTTLS no firewall do servidor.",
    html: "<p>Preciso liberar a porta 587 com STARTTLS no firewall do servidor.</p>",
    texto: "Liberar porta 587.",
    data_envio: hours(30),
    lida: true,
    favorita: false,
    pasta: "drafts",
    anexos: [],
  },
  {
    id: "e9",
    message_id: "<9@malaca.com.br>",
    remetente: { nome: "Promoções Turbo", email: "ofertas@turbo-deals.biz" },
    destinatarios: [{ email: "contato@malaca.com.br" }],
    assunto: "VOCÊ FOI SELECIONADO!!! prêmio liberado",
    preview: "Clique agora para resgatar seu prêmio exclusivo antes que expire.",
    html: "<p>Clique agora para resgatar seu prêmio.</p>",
    texto: "Spam.",
    data_envio: hours(12),
    lida: false,
    favorita: false,
    pasta: "spam",
    anexos: [],
  },
  {
    id: "e10",
    message_id: "<10@malaca.com.br>",
    remetente: { nome: "Antigo Provedor", email: "billing@antigoprovedor.com" },
    destinatarios: [{ email: "contato@malaca.com.br" }],
    assunto: "Cancelamento de conta concluído",
    preview: "Sua conta foi encerrada e nenhuma cobrança futura será feita.",
    html: "<p>Sua conta foi encerrada e nenhuma cobrança futura será feita.</p>",
    texto: "Conta encerrada.",
    data_envio: hours(140),
    lida: true,
    favorita: false,
    pasta: "trash",
    anexos: [],
  },
];
